### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by xupsh** [wbrueckner/cv2pynq#1]
https://github.com/wbrueckner/cv2pynq/blob/7bd90c00de9e42b071d507a7587cb99bbf120bd7/cv2pynq/cv2pynq.py#L295

https://github.com/wbrueckner/cv2pynq/blob/7bd90c00de9e42b071d507a7587cb99bbf120bd7/cv2pynq/cv2pynq.py#L302

**Comment by wbrueckner** [comment]
fixed in 193ab7e15382a20fc1f99a8e3dc669f7a87600c5
